# Generated by Django 2.2.2 on 2019-06-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(error_messages={'unique': 'This phone number is already associated with a member'}, max_length=12, unique=True)),
                ('role', models.CharField(default='regular', max_length=25)),
            ],
        ),
    ]
