# Generated by Django 2.2.2 on 2019-06-29 03:22

from django.db import migrations


def remove_duplicate_emails(apps, schema_editor):
    TeamMember = apps.get_model('instateam', 'TeamMember')
    all_emails = [m.email for m in TeamMember.objects.all()]
    duplicate_emails = [e for e in all_emails if all_emails.count(e) > 1]
    for email in duplicate_emails:
        member_set = [m for m in TeamMember.objects.filter(email=email)]
        for i in range(1, len(member_set)):
            mb = member_set[i]
            new_email = mb.email.split('@')[0] + '+' + str(i) + '@' + mb.email.split('@')[1]
            mb.email = new_email
            mb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('instateam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_emails)
    ]
