# Generated by Django 2.2.2 on 2019-06-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instateam', '0002_auto_20190629_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
