# Generated by Django 2.2.2 on 2019-07-03 18:45

import re
from django.db import migrations


def format_phone_numbers(apps, schema_editor):
    """
    Data migration updating the phone number format of all TeamMember instances
    from 222-333-4444 to +12223334444 which is compliant with django-phonenumber-field's 
    PhoneNumberField, allowing the next database schema migration replacing the CharField 
    with a PhoneNumberField to run smoothly afterward.
    """
    # make sure to remove the phone field validation contraints before running this
    TeamMember = apps.get_model('instateam', 'TeamMember')
    for mb in TeamMember.objects.all():
        new_phone = '+1' + re.sub('-', '', mb.phone)
        mb.phone = new_phone
        mb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('instateam', '0003_auto_20190629_0335'),
    ]

    operations = [
        migrations.RunPython(format_phone_numbers)
    ]