# Generated by Django 2.2.2 on 2019-07-03 18:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('instateam', '0004_auto_20190703_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'This phone number is already associated with a member'}, max_length=128, region=None, unique=True),
        ),
    ]
